services:
  app:
    container_name: ${APP_NAME}_${APP_ENV}_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.contacts.rule=Host(`${APP_HOST}`)"
      - "traefik.http.services.contacts.loadbalancer.server.port=8080"
    volumes:
      - .:/var/www/html
    networks:
      - default
      - proxynet

  db:
    container_name: ${APP_NAME}_${APP_ENV}_db
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    container_name: ${APP_NAME}_${APP_ENV}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.${APP_HOST}`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    networks:
      - default
      - proxynet

volumes:
  db_data:

networks:
  proxynet:
    name: proxy_network
    external: true